name: Live Snake

on:
  schedule:
    - cron: "*/5 * * * *" # каждые 5 минут
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate Snake SVG
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: node generate_snake.js

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
